# -*- coding: utf-8 -*-
"""Wet_and_dry_YOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_t4_Uv1HThPGfktu0U_b-MycEmSpGFT
"""

!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
!mkdir /content/datasets
# %cd /content/datasets

!pip install roboflow --quiet


from roboflow import Roboflow
rf = Roboflow(api_key="ruLKzuJIJZXiXUMoKCEg")
project = rf.workspace("george-p-zacharia-zbzd5").project("hackfinal-wet")
dataset = project.version(4).download("folder")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!yolo task=classify mode=train model=yolov8n-cls.pt data={dataset.location} epochs=50 imgsz=128

!ls -la /content/runs/classify/train4/

!cat /content/runs/classify/train4/results.csv | head -10

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/

!yolo task=classify mode=val model=/content/runs/classify/train4/weights/best.pt data={dataset.location}

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'/content/runs/classify/predict2/*.jpg')[:3]:
      display(Image(filename=image_path, width=600))
      print("\n")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/
!yolo task=classify mode=predict model=/content/runs/classify/train4/weights/best.pt conf=0.25 source={dataset.location}/test/Wet

